accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup, practice

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name = "login"),
    path("logout/", auth_views.LogoutView.as_view(), name = "logout"),
    path("signup/", signup, name = "signup"),
    path("", practice, name = "account_practice"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path('accounts/', include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import(
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
    MoneyViewList,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name = "home"),
    path("create/", ReceiptCreateView.as_view(), name = "create_receipt" ),
    path("accounts/", AccountListView.as_view(),  name = "account"),
    path("categories/", ExpenseCategoryListView.as_view(), name = "list_categories"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name = "create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name = "create_account"),
    path("money/", MoneyViewList.as_view(), name = "list_money"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from tkinter import CASCADE
from django.db import models
from django.conf import settings
from django.forms import DecimalField

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length= 50)
    owner = models.ForeignKey( USER_MODEL, 
    related_name="categories", 
    on_delete= models.CASCADE,)
    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length= 100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name= "accounts", on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField( decimal_places=3 ,max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey( USER_MODEL, 
    related_name="receipts", 
    on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", 
        related_name="receipts", 
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account", 
        related_name="receipts", 
        on_delete=models.CASCADE, 
        null = True,
    )

class Money(models.Model):
    cash = models.DecimalField(decimal_places= 2, max_digits=10)

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import login
from receipts.models import Receipt
# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(username = request.POST.get("username"), password = request.POST.get("password"),)
            new_user.save()
            login(request, new_user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {"form" : form,}
    return render(request, "registration/signup.html", context)

def practice(request):
    list = Receipt.objects.all()
    dabadoo = []
    for l in range(0, 10):
        dabadoo.append("horse")
    print("fish")
    context = {
        "practices_list": list,
        "numby" : dabadoo,
    }

    response = render(request, "accounts/list2.html", context)

    return response
            

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import Money, Receipt, Account, ExpenseCategory
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = ("receipts/list.html")
    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = ("receipts/create.html")
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = ("accounts/list.html")
    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = ("accounts/create.html")
    fields = ["name", "number"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = ("e_categories/list.html")
    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = ("e_categories/create.html")
    fields = ["name"]
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")

class MoneyViewList(LoginRequiredMixin, ListView):
    model= Money
    template_name = "money/list.html"
    fields = ("cash")
    def form_valid(self, form):
        item = form.save(commit=False)
        item.save()
        return redirect("home")

accounts/templates/accounts/list2.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>My Accounts</h1>
    <table>
        <thead>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </thead>
        <tbody>
            {% for r in practices_list %}
            <p>hello</p>
            <td>{{ r.vendor }}</td>
            <td>{{ numby }}</td>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>My Accounts</h1>
    <table>
        <thead>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </thead>
        <tbody>
            {% for account in account_list %}
            <tr>
                <td>
                    {{ account.name }}
                </td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title></title>
    <nav>
        <ul>
            <a href="{% url 'list_money' %}"> . </a>
            <table>
                <tbody>
                    <td>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a href="{% url 'account_practice' %}">practice</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Sign Up</li>
                        {% endif %}
                    </td>
                    <td>
                        {% if user.is_authenticated %}
                    <td>
                        <li>
                            <a href="{% url 'home' %}">View Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'create_receipt' %}">Create Receipt</a>
                        </li>
                    </td>
                    <td>
                        <li>
                            <a href="{% url 'create_category' %}">Create Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">View Categories</a>
                        </li>
                    </td>
                    <td>
                        <li>
                            <a href="{% url 'create_account' %}">Create Account</a>
                        </li>
                        <li>
                            <a href="{% url 'account' %}">View Account</a>
                        </li>
                    </td>
                    {% endif %}
                    </td>
                </tbody>
            </table>
        </ul>
    </nav>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

receipts/templates/e_categories/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/e_categories/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Expense Categories</h1>
    <div>
        <a href="{% url 'create_category' %}">Create Categories</a>
    </div>
    <table>
        <thead>
            <th>Name</th>
            <th>Number of receipts</th>
        </thead>
        <tbody>
            {% for category in expensecategory_list%}
            <tr>
                <td>
                    {{ category.name }}
                </td>
                <td>{{ category.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/money/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Secret Money</h1>
    <div>
    </div>
    <table>
        <thead>
            <th>Dollar</th>
        </thead>
        <tbody>
            {% for category in money_list%}
            <tr>
                <td>
                    {{ category.cash }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>My Receipts</h1>
    <table>
        <thead>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>
                <td>
                    {{ receipt.vendor }}
                </td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date|date:"m/d/y"}}</td>
                <td>{{ receipt.category.name }}</td>
                <td>{{ receipt.account.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        {% csrf_token %}
    </div>
</main>
{% endblock content %}